on:  
    pull_request:
        branches:
            - master
jobs:
    test:
        name: Build C# Main App
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-dotnet@v3
          with:
           dottnet-version: '6.0.x'
        - run: dotnet build AssetEditor\AssetEditor.csproj